### ISSUE TITLE
Question: Do you know how many system copies this does?

### ISSUE THREAD

**Issue by Suhail** [devowlio/node-fdkaac#5]
Do you have any idea how many system memory copies this is doing vs just utilizing pointers? I am curious about benchmarks wrt to CPU where it might be higher than say if you wrote it all in C++. If it's equivalent since it utilizes FFmpeg & the byte buffers are references that would be amazing to know.

**Comment by jankarres** [comment]
No, I did not measure these numbers. But I can agree that it is more performant when written in pure C++. Feel free to give some numbers here if you have tested that.

On the other hand, most of the work, transcoding the audio files, is done by a native binding/execution of `ffmpeg'. In comparison, handling and parsing of the `stdout' stream, which is done by `node-fdkaac', should be tiny fraction of CPU usage.
