### ISSUE TITLE
Need FDKAAC issue

### ISSUE THREAD

**Issue by hoorrus** [devowlio/node-fdkaac#7]
I followed all the instructions, but I am still getting the same error message. 

`You need fdkaac to be installed for using audio profiles`

**Comment by jankarres** [comment]
Have you run the installer as explained in https://github.com/devowlio/node-fdkaac#run-on-debian?

**Comment by jankarres** [comment]
Great to hear you made it through the installation.

Regarding your further question, please open a new ticket with a demo to reproduce the problem if necessary. Then I can help you if necessary.
